# Generated by Django 4.2.9 on 2024-01-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name_uk',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
