# Generated by Django 4.2.9 on 2024-01-27 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_menuitem_description_en_menuitem_description_es_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='name_en',
        ),
    ]
