# Generated by Django 4.2.9 on 2024-01-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_remove_menuitem_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
