# Generated by Django 4.2.9 on 2024-01-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_menuitem_description_en_menuitem_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
